### ISSUE TITLE
ARM vs. x86

### ISSUE THREAD

**Issue by xloading** [sean-hill/ionic-gulp-release#1]
Hi Sean!

Thanks a lot for very useful solution shared with community.

Though I'm experimenting with Ionic for quite a while already I'm still rather new to Gulp and android building techniques therefore my question may sound dumb :)

In your code you sign and release two files (armv7 and x86).
Am I right that this applies only to Crosswalk builds (which produces both versions) and generally this is not required for default Ionic builds (e.g. my Ionic v1 creates single debug apk)?
Is there any sense to apply this splitting logic for single default build if I'm not going to support Android < 4.4 (i.e. utilise Crosswalk) in nearest future?

Thank you very much in advance!

Georgy

**Comment by xloading** [comment]
Btw I had also to add "path" and "child_process" to below command from the doc:
```
npm install --save-dev gulp run-sequence shelljs async path child_process
```

**Comment by xloading** [comment]
Aaand one more notice :)
I was surprised myself but when you have two platforms (iOS and Android) then the order of arguments in command DOES really matter:
```
ionic build --release android 
```
- builds BOTH platforms, while
```
ionic build android --release 
``` 
- builds only Android as required.

Don't know if it should be reported as Ionic v1 bug or not...

**Comment by sean-hill** [comment]
Hey @xloading this repo is a bit outdated now since Ionic is much more awesome 😄  You are correct, you should only need one build now if you don't plan on using Crosswalk. Take a look at how awesome Ionic is now with their [Ionic Package](https://ionicframework.com/products/#packaging) service and specifically the [docs](https://docs.ionic.io/services/package/) regarding it. I'd recommend using their service instead of a manual process like this repo 👍
